import { CompanySnapshot } from "@/types/letterhead";

type Props = { company: CompanySnapshot; showHeader: boolean; showFooter: boolean };

const Footer = ({ company }: { company: CompanySnapshot }) => (
  <footer className="border-t px-8 py-3 text-xs text-slate-600">{company.address} | {company.phone} | {company.email} | GST: {company.gst}</footer>
);

export function TemplateMinimal({ company, showHeader, showFooter }: Props) {
  return <div>{showHeader && <header className="px-8 py-4 font-semibold">{company.name}</header>}{showFooter && <Footer company={company} />}</div>;
}

export function TemplateCenteredLogo({ company, showHeader, showFooter }: Props) {
  return <div>{showHeader && <header className="px-8 py-6 text-center text-xl font-bold">{company.name}</header>}{showFooter && <Footer company={company} />}</div>;
}

export function TemplateTopColorBar({ company, showHeader, showFooter }: Props) {
  return <div>{showHeader && <header><div className="h-2" style={{ background: company.primaryColor }} /><div className="px-8 py-3">{company.name}</div></header>}{showFooter && <Footer company={company} />}</div>;
}

export function TemplateLeftStripe({ company, showHeader, showFooter }: Props) {
  return <div className="border-l-8" style={{ borderColor: company.primaryColor }}>{showHeader && <header className="px-8 py-4">{company.name}</header>}{showFooter && <Footer company={company} />}</div>;
}

export function TemplateModernClean({ company, showHeader, showFooter }: Props) {
  return <div>{showHeader && <header className="flex items-center justify-between px-8 py-4"><strong>{company.name}</strong><span>{company.website}</span></header>}{showFooter && <Footer company={company} />}</div>;
}

export function TemplateLegalFooter({ company, showHeader, showFooter }: Props) {
  return <div>{showHeader && <header className="px-8 py-4"><h2 className="text-lg font-semibold">{company.name}</h2></header>}{showFooter && <footer className="bg-slate-50 px-8 py-4 text-xs">This document is electronically generated by {company.signatory}. Registered GST: {company.gst}. Contact: {company.address}.</footer>}</div>;
}
